version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: dangbei/api-proxy:latest  # 添加了镜像名称配置
    container_name: db-api-service  # 添加了容器名配置
    ports:
      - "8000:8000"
    environment:
      - API_KEY=sk_gUXNcLwm0rnnEt55Mg8hq88
      - API_DOMAIN=https://ai-api.dangbei.net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 3